config/routes.rb
Helpdesk::Application.routes.draw do
  resources :tickets
  resources :inbounds, only: :create

end

app/models/inbound.rb
class Inbound < ActiveRecord::Base
  belongs_to :ticket

  def self.create_from_inbound_hook(message)
    id = message["Subject"]
    ticket_id = id[/(?<=#)\d+/]
    self.new(:text => message["TextBody"], :ticket_id => ticket_id.to_i)
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :inbounds

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inbounds_controller.rb
class InboundsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def create
    @inbound = Inbound.create_from_inbound_hook(Postmark::Json.decode(request.body.read))

    @inbound.save
    render nothing: true
  end

private
    # Never trust parameters from the scary internet, only allow the white list through.
    def inbound_params
      params.require(:inbound).permit(:text, :user_email, :ticket_id)
    end

end


# @ticket = Ticket.create_from_inbound_hook(Postmark::Json.decode(request.body.read))
#   def self.create_from_inbound_hook(message)
#     self.update(message["Subject"].gsub("Re: ", ""), :reply => message["TextBody"])
#   end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @inbounds = Inbound.all
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        TicketMailer.bug_fix(@ticket).deliver
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json


  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :body, :email, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inbound_helper.rb
module InboundHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpdesk</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <span>Contact Email:</span>
    <%= f.text_field :email %>
    <span>Error:</span>
    <%= f.text_field :title %> <br>
    <span>Details:</span>
    <%= f.text_area :body %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.email %> </td>
        <td><%= ticket.title %> </td>
        <td><%= ticket.body %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>
      <td><%= @ticket.email %> </td>
        <td><%= @ticket.title %> </td>
        <td><%= @ticket.body %></td>
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

<% @ticket.inbounds.each do |reply| %>
  <p><%= reply.body %></p>
<% end %>